name: build

on: [ push ]

jobs:
  build:
    name: gradle build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Build
        run: |
          ./gradlew build